version: '3.8'

services:
  server:
    build:
      context: ./
      dockerfile: ./dockerfiles/nginx.dockerfile
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: ./
      dockerfile: ./dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
    ports:
      - 3306:3306
    volumes:
      - laravel-data:/var/lib/mysql

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    stdin_open: true
    tty: true

  artisan:
    build:
      context: ./
      dockerfile: ./dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ['php', '/var/www/html/artisan']

  npm:
    image: node:14-alpine
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    entrypoint: ['npm']

volumes:
  laravel-data:
